# Generated by Django 3.1.7 on 2021-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
